Added "Core" layer for solution
s-samusik/DatasetMarketplace pull request #2
Opened 2021-04-30 13:36 UTC by s-samusik

2021-05-07 13:05 UTC, DzmitryBratchuk commented on DatasetMarketplace.Domain/Entities/OrderCard.cs
> +        public PaymentType PaymentType { get; set; }
Mark as nullable

2021-05-08 14:31 UTC, s-samusik commented on DatasetMarketplace.Data/DatasetMarketplace.Data.csproj
> +    <RootNamespace>DatasetMarketplace.Data</RootNamespace>
I'm going to use this project for repositories (interfaces and implementation). Maybe name of project is incorrect.
I remember you suggested me work repositories in once project, don't sesparate interfaces and implementation on different layers. 
Or maybe i need to work with repositories in "Persistence" layer and rename "Persistence" to "DataAccess" or better "Infrastructure"? 
Also i have variant to move interfaces of repositories in "Persistence" and implement it in "Data" layer and renamed "Data" to "Infrastructure".
I don't know which variant is right becouse there is have no only right variant here.

2021-05-09 12:27 UTC, DzmitryBratchuk requested changes

2021-05-09 12:27 UTC, DzmitryBratchuk commented on DatasetMarketplace.Api/Startup.cs
> +                options.UseNpgsql(Configuration["DatasetMarketlpace:PostgreSQL"]));
Return this change back.

And return change in json file, but just don't push your credentials. Do like this:

> `"ConnectionStrings": {`
>     `"PostgreSQL": "<connection string>"`
>   `},`

2021-05-09 12:27 UTC, DzmitryBratchuk commented on DatasetMarketplace.Domain/Entities/User.cs
> +        public virtual ICollection<Role> UserRoles { get; set; } = new HashSet<Role>();
```suggestion
        public virtual ICollection<Role> Roles { get; set; } = new HashSet<Role>();
```

2021-05-09 12:27 UTC, DzmitryBratchuk commented on DatasetMarketplace.Persistence/Configurations/UserRoleConfiguration.cs
> +    public class UserRoleConfiguration : IEntityTypeConfiguration<Role>
```suggestion
    public class RoleConfiguration : IEntityTypeConfiguration<Role>
```

2021-05-09 12:27 UTC, DzmitryBratchuk commented on DatasetMarketplace.Persistence/DatasetMarketplaceContext.cs
> +        public virtual DbSet<Role> UserRoles { get; set; }
```suggestion
        public virtual DbSet<Role> Roles { get; set; }
```

2021-05-09 12:27 UTC, DzmitryBratchuk commented on DatasetMarketplace.Persistence/Configurations/UserConfiguration.cs
> +            builder.Property(x => x.FirstName);
Do we really need code lines like this. We do nothing with property?

2021-05-09 12:27 UTC, DzmitryBratchuk commented on DatasetMarketplace.Persistence/Configurations/PlacementCardConfiguration.cs
> +            builder.Property(x => x.DatasetId);
The same...

2021-05-09 12:27 UTC, DzmitryBratchuk commented on DatasetMarketplace.Persistence/Configurations/DatasetConfiguration.cs
> +            builder.Property(x => x.Description);
The same...

2021-05-09 12:27 UTC, DzmitryBratchuk commented on DatasetMarketplace.Domain/Enums/CardStatus.cs
> +        Successed
Values must be explicitly specified for all elements of the enums.

2021-05-09 12:27 UTC, DzmitryBratchuk commented on DatasetMarketplace.Domain/Entities/Role.cs
> +        public RoleType Name { get; set; }
public RoleType RoleType { get; set; } or public RoleType Type { get; set; }

2021-05-09 12:31 UTC, DzmitryBratchuk commented on DatasetMarketplace.Data/DatasetMarketplace.Data.csproj
> +    <RootNamespace>DatasetMarketplace.Data</RootNamespace>
> Or maybe i need to work with repositories in "Persistence" layer and rename "Persistence" to "DataAccess" or better "Infrastructure"?

I prefere this one. Work with repositories in "Persistence" layer and rename "Persistence" to "Data" or "DataAccess"

2021-05-10 10:45 UTC, DzmitryBratchuk approved these changes

2021-05-10 10:45 UTC, merged