Interfaces, repositories, services
s-samusik/DatasetMarketplace pull request #4
Opened 2021-05-13 17:00 UTC by s-samusik

.DataAccess - created interfaces and implemented repositories.
.Applicaton - created interfaces and implemented services.
.Api - added Swagger and Autofac.

2021-05-14 14:39 UTC, DzmitryBratchuk requested changes

2021-05-14 14:39 UTC, DzmitryBratchuk commented on DatasetMarketplace.DataAccess/DataAccessExtension.cs
> +                    x.FullName.Contains(".DataAccess"));
I'm sure you can write like this:
var assembly = typeof(DataAccessExtension).Assembly;
or
var assembly = typeof(UserRepository).Assembly;

2021-05-14 14:39 UTC, DzmitryBratchuk commented on DatasetMarketplace.Domain/Enums/CardStatus.cs
> -        Processing = 2,
Why Processing was removed?)

2021-05-14 14:39 UTC, DzmitryBratchuk commented on DatasetMarketplace.DataAccess/Repositories/UserRepository.cs
> +                .Where(x => x.Roles.Any(x => x.UserRole == userRole.UserRole))
I can't understand what is going on in this line
Wtf?  x.UserRole == userRole.UserRole

2021-05-14 14:39 UTC, DzmitryBratchuk commented on DatasetMarketplace.DataAccess/Repositories/UserRepository.cs
> +        public async Task<List<User>> GetAllByRoleAsync(Role userRole)
```suggestion
        public async Task<List<User>> GetAllByRoleAsync(Role role)
```
Why not like this?

2021-05-14 14:39 UTC, DzmitryBratchuk commented on DatasetMarketplace.Domain/Enums/UserRole.cs
> +    public enum UserRole
public enum RoleType is better.
In my opinion this can prevent problems with understanding the code.

2021-05-14 14:39 UTC, DzmitryBratchuk commented on DatasetMarketplace.DataAccess/UnitOfWork.cs
> +            this.context = context;
_context = context;

2021-05-14 14:39 UTC, DzmitryBratchuk commented on DatasetMarketplace.DataAccess/UnitOfWork.cs
> +        private IUserRepository userRepository;
Add _ at the beginning

2021-05-14 14:39 UTC, DzmitryBratchuk commented on DatasetMarketplace.DataAccess/Repositories/BaseRepository.cs
> +        private readonly DatasetMarketplaceContext context;
_context

2021-05-15 09:16 UTC, s-samusik commented on DatasetMarketplace.DataAccess/DataAccessExtension.cs
> +                    x.FullName.Contains(".DataAccess"));
Thanks. You are right as always.

2021-05-15 10:03 UTC, s-samusik commented on DatasetMarketplace.Domain/Enums/CardStatus.cs
> -        Processing = 2,
I thought like this:
- first stage - a card created, received the status "pending";
- second stage - a creator decided to cancel the card, status -"canceled";
- third stage - an employee, using the "ReviewCard" method, changes the status of the card to "failed" or "successful" (i will add check for these statuses).

If I need to add the "processing" status, I will have to create a "TakeForCheck" method. And this method will only change the status of the card from "pending" to "processing". Right?
I can implement this.
P.S. I just thought without this status we have a card with the status "pending", and then we receive result of pend - "failed" or "successed".

2021-05-15 11:11 UTC, s-samusik commented on DatasetMarketplace.DataAccess/Repositories/UserRepository.cs
> +                .Where(x => x.Roles.Any(x => x.UserRole == userRole.UserRole))
Users and roles have relationships "many-to-many". And i want to get all users with a specific role. 
To solve this, I read these articles below. And using method "Any()", I get those records from the table that match condition "role from table == role.UserRole". It is not right? Or could you please help me with this moment?

https://smehrozalam.wordpress.com/2010/06/29/entity-framework-queries-involving-many-to-many-relationship-tables/

https://entityframework.net/knowledge-base/30466696/query-a-many-to-many-relationship-with-linq-entity-framework--codefirst

https://stackoverflow.com/questions/40474349/linq-many-to-many-where

2021-05-16 17:13 UTC, DzmitryBratchuk commented on DatasetMarketplace.Domain/Enums/CardStatus.cs
> -        Processing = 2,
"Pending" is the period of time when card was created, but the employee has not yet started working on it. 
"Processing" is the time when the employee processes the card.

2021-05-16 17:26 UTC, DzmitryBratchuk requested changes

2021-05-16 17:26 UTC, DzmitryBratchuk commented on DatasetMarketplace.DataAccess/DataAccessExtensions.cs
> +            builder.RegisterAssemblyTypes(assembly)
Also when register don't forget about "Instance Scope"

2021-05-16 17:26 UTC, DzmitryBratchuk commented on DatasetMarketplace.Domain/Entities/Role.cs
> +        public RoleType UserRole { get; set; }
Why property name is UserRole???
RoleType better
Type the best

2021-05-16 17:28 UTC, DzmitryBratchuk commented on DatasetMarketplace.DataAccess/Repositories/UserRepository.cs
> +                .Where(x => x.Roles.Any(x => x.UserRole == userRole.UserRole))
I'm about naming, now it's better

2021-05-16 17:44 UTC, DzmitryBratchuk requested changes

2021-05-16 17:44 UTC, DzmitryBratchuk commented on DatasetMarketplace.Api/Controllers/CompanyController.cs
> +
_ at the beginning

2021-05-16 17:44 UTC, DzmitryBratchuk commented on DatasetMarketplace.Api/AutoMapperProfile.cs
> +using DatasetMarketplace.Domain.Entities;
Why you are using models from Domain here?  
Here should be conversions from DatasetMarketplace.Api models to DatasetMarketplace.Application models

2021-05-16 17:44 UTC, DzmitryBratchuk commented on DatasetMarketplace.Api/AutoMapperProfile.cs
> +            CreateMap<CompanyCreateDTO, Company>();
CompanyCreateDto

2021-05-16 17:59 UTC, DzmitryBratchuk requested changes

2021-05-16 17:59 UTC, DzmitryBratchuk commented on DatasetMarketplace.Api/Controllers/CompanyController.cs
> +        public async Task<IActionResult> CreateAsync(CompanyCreateDTO companyDTO)
You must use model that should be defined in DatasetMarketplace.Api

2021-05-16 17:59 UTC, DzmitryBratchuk commented on DatasetMarketplace.Api/Validations/Company/CompanyCreateValidator.cs
> +    public class CompanyCreateValidator : AbstractValidator<CompanyCreateDTO>
Not Dto here. You must use model that should be define in DatasetMarketplace.Api

2021-05-16 17:59 UTC, DzmitryBratchuk commented on DatasetMarketplace.Api/Controllers/CompanyController.cs
> +        [HttpPost("")]
Just [HttpPost]

2021-05-16 17:59 UTC, DzmitryBratchuk commented on DatasetMarketplace.Api/Controllers/CompanyController.cs
> +            }
This is useless cause you use FluentValidation.
And read about ProducesResponseType attribute.

2021-06-03 14:46 UTC, DzmitryBratchuk requested changes

2021-06-03 14:46 UTC, DzmitryBratchuk commented on DatasetMarketplace.Api/ApiMappingProfile.cs
> +
2 empty lines are too many. Use 1 empty line in this cases

2021-06-03 14:46 UTC, DzmitryBratchuk commented on DatasetMarketplace.Api/ApiMappingProfile.cs
> +
Use 0 empty line in this cases

2021-06-03 14:46 UTC, DzmitryBratchuk commented on DatasetMarketplace.Api/ApiMappingProfile.cs
> +
Remove empty lines

2021-06-03 14:46 UTC, DzmitryBratchuk commented on DatasetMarketplace.Api/Controllers/CompaniesController.cs
> +
Remove empty line

2021-06-03 14:46 UTC, DzmitryBratchuk commented on DatasetMarketplace.Api/Controllers/CompaniesController.cs
> +                count = response.Count,
Why we also return count? Method name is "GetAllAsync" not like "GetAllAndCountAsync". In this case, the client himself will be able to calculate the number of companies that we returned to him.

If you need just calculate the number of companies and return to client, you can create method like "GetCountAsync"

2021-06-03 14:46 UTC, DzmitryBratchuk commented on DatasetMarketplace.Api/Controllers/CompaniesController.cs
> +                count = response.Count,
See above.

2021-06-03 14:46 UTC, DzmitryBratchuk commented on DatasetMarketplace.Api/Controllers/CompaniesController.cs
> +
There should be no business logic in the controller. In this case "GetAsync(request.Id)" is part of logic

2021-06-03 15:42 UTC, DzmitryBratchuk requested changes

2021-06-03 15:42 UTC, DzmitryBratchuk commented on DatasetMarketplace.Api/Controllers/CompaniesController.cs
> +        [HttpPut("{id}")]
You must use this id, but you don't.

2021-06-03 15:42 UTC, DzmitryBratchuk commented on DatasetMarketplace.Api/Models/Company/UpdateCompanyRequest.cs
> +        public Guid Id { get; set; }
Id you can get from route in controller Put action. This is update model, Id useless here cause you can't update Id field.

2021-06-03 15:42 UTC, DzmitryBratchuk commented on DatasetMarketplace.Api/Validations/UpdateCompanyValidator.cs
> +            RuleFor(x => x.Id).NotEmpty();
Rules for Name, Country ....?

2021-06-03 15:42 UTC, DzmitryBratchuk commented on DatasetMarketplace.Api/Models/User/CreateUserRequest.cs
> +        public string Password { get; set; }
Need ConfirmPassword field

2021-06-03 15:42 UTC, DzmitryBratchuk commented on DatasetMarketplace.Api/Models/User/UpdateUserRequest.cs
> +        public string Password { get; set; }
For password changes please use separate controller action with its own model

2021-06-04 12:01 UTC, DzmitryBratchuk requested changes

2021-06-29 07:01 UTC, merged